{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.signal import find_peaks\n",
    "\n",
    "import os, sys, glob\n",
    "import tensorflow as tf\n",
    "import keras\n",
    "from keras.layers import Dense, Activation, Dropout, Input, LSTM, Reshape, Lambda, RepeatVector, CuDNNLSTM, Reshape\n",
    "from keras.optimizers import RMSprop, Adam\n",
    "from keras.callbacks import ModelCheckpoint\n",
    "from keras.utils import multi_gpu_model\n",
    "from keras.models import load_model, Model\n",
    "from keras import backend as K\n",
    "from keras.models import load_model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "MAGNETIC_FIELD = 403            # Unit: Gauss\n",
    "GYRO_MAGNETIC_RATIO = 1.07*1000 # Unit: Herts\n",
    "wl = MAGNETIC_FIELD*GYRO_MAGNETIC_RATIO*2*3.14\n",
    "\n",
    "t = np.load('../../../../../TimTaminiau/20190610_time_no_duplicated.npy')[:13500]*1e-6"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [],
   "source": [
    "def exact(AB_list):\n",
    "    M_list_temp = 1\n",
    "    for A, B in AB_list:\n",
    "        mz = (A + wl) / wl\n",
    "        mx = B / wl\n",
    "        w_tilda = pow(pow(A+wl, 2) + B*B, 1/2)\n",
    "        alpha = w_tilda * t\n",
    "        beta = wl * t\n",
    "\n",
    "        phi = np.arccos(np.cos(alpha) * np.cos(beta) - mz * np.sin(alpha) * np.sin(beta))\n",
    "        K1 = (1 - np.cos(alpha)) * (1 - np.cos(beta))\n",
    "        K2 = 1 + np.cos(phi)\n",
    "        K = pow(mx,2) * (K1 / K2)\n",
    "        M_list_temp *= (1 - K * pow(np.sin(32 * phi/2), 2))\n",
    "    return (M_list_temp + 1) / 2\n",
    "\n",
    "def N(A, B):\n",
    "    M_list_temp = 1\n",
    "    w_tilda = pow(pow(A+wl, 2) + B*B, 1/2)\n",
    "    mz = (A + wl) / w_tilda\n",
    "    mx = B / w_tilda\n",
    "\n",
    "    alpha = w_tilda * t\n",
    "    beta = wl * t\n",
    "    phi = np.arccos(np.cos(alpha) * np.cos(beta) - mz * np.sin(alpha) * np.sin(beta))\n",
    "    K1 = mx * mx * (1 - np.cos(alpha)) * (1 - np.cos(beta)) / 2\n",
    "    K2 = 32 * np.cos(8 * phi) * np.cos(4 * phi) * np.cos(2 * phi) * np.cos(phi) * np.sin(phi / 2)\n",
    "    return K1 * K2**2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [],
   "source": [
    "def make_heatmap(p):\n",
    "    A_list = np.linspace(-60000, 60000, 80)\n",
    "    B_list = np.linspace(2000, 70000, 17)\n",
    "    indexer = 0\n",
    "    heatmap = np.zeros((80, 17))\n",
    "    tp = np.load('/data1/keras_model/filter_indices.npy').item()\n",
    "    p_x1x = p * (1 - p);\n",
    "    for i, A in enumerate(A_list):\n",
    "        print(i)\n",
    "        for j, B in enumerate(B_list):\n",
    "            os.environ[\"CUDA_VISIBLE_DEVICES\"] = '1'\n",
    "            config = tf.ConfigProto(device_count = {'XLA_GPU' : 0})\n",
    "            config.gpu_options.allow_growth = True\n",
    "            sess = tf.Session(config=config)\n",
    "            keras.backend.set_session(sess)\n",
    "\n",
    "            dir_name = '/data1/keras_model/' + str(indexer)\n",
    "            for file in os.listdir(dir_name):\n",
    "                if file.endswith(\".h5\"):\n",
    "                    model = load_model(dir_name + '/' + file)\n",
    "                    if j in (0, 1, 2):\n",
    "                        heatmap[i][j] = model.predict(p_x1x[tp[indexer]].transpose()).item()\n",
    "                    else: \n",
    "                        heatmap[i][j] = model.predict(p[tp[indexer]].transpose()).item()\n",
    "            indexer += 1\n",
    "            keras.backend.clear_session()\n",
    "            sess.close()\n",
    "            \n",
    "    return heatmap"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {},
   "outputs": [],
   "source": [
    "exp_data_tmp = np.load('../../../../../TimTaminiau/20190610_exp_data_24200.npy')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c39ed86a0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa11735f4e0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9cb4f819e8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3b61c710>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa0d0153438>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c4377f320>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa0d8076978>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9ca43fb2b0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3b679f28>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "5\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c29b39898>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa1172eeac8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa1e427ac50>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "6\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9ca64d5ef0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "7\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c4103b6a0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9ca4473ef0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "8\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9ca8b3d898>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa0d8459ef0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3835fdd8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "9\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c388e80b8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "10\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c422aa710>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9ca8b3d0b8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "11\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c29b39048>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c38104438>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c403ec390>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "12\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c38280780>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "13\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9ca45064a8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c388eaa90>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "14\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9ca49e9f98>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c2bff7630>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa0d815d940>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "15\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c388eacf8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "16\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c85864240>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c401d2860>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "17\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c40d8aba8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3b1216a0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c38bbc128>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "18\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c87e94358>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "19\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa0e011eeb8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c85816588>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3835fb70>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c4102da58>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c38bbca58>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "21\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9ca64d5e80>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "22\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c388c7940>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3821bb70>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "23\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c41001cc0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa0d0729f60>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c38b8d128>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "24\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c4046e6d8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "25\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c4c9b09b0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9ca3d9b828>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "26\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c38a27c88>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa1080736a0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c380b4dd8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "27\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c422aa128>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "28\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa11c8bbe48>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c4047bf28>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "29\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa108073780>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa108074128>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c403fb6d8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "30\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa11c7da0f0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c87e945f8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9cb4f862e8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "32\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3b8e4be0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c868506a0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa11014b7f0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "33\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa0d00f49e8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "34\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c4ea40e10>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa0c87c6208>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "35\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c29a71550>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3811ca90>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c422aaa90>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "36\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c422caeb8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "37\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c4049bdd8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c404437f0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "38\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c386c8390>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c401f9a90>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c857fc438>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "39\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa0d84be358>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "40\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c403fbeb8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c388dca58>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "41\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa11006b978>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c388f06a0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa117d466d8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "42\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c40402438>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "43\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c4c86cb00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3b91df60>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "44\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa0d85a47b8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3b6366a0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c857fc668>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "45\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9d1d01a160>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "46\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c90795668>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa0d03a2240>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "47\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa10806deb8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa0d02116d8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3835f278>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "48\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c85816940>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "49\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c29b39710>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c2b69ab38>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "50\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c403fbe48>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c381506a0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c29b17860>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "51\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c4ea40fd0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "52\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa0d075df98>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9ca49eaa20>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "53\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c2b4c9940>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c40ddea58>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c7a3a0780>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "54\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9d1d00dd30>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "55\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c38a27208>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c4c9b0828>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "56\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa114f38d30>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c42d73240>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa0d81b4748>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "57\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c2bfd7d68>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "58\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3aa836d8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c40de24a8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "59\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c8684f748>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c4040da20>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c42d84a90>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "60\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3b929438>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "72\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c40d8af28>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "73\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3834c518>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3b8e41d0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "74\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c4103b470>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa1080a79e8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa0d06ba780>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "75\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c38b8d668>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "76\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9ca42935c0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c403e4940>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "77\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3835ff98>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c40f95240>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c40d8ab70>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "78\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c3b61c470>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "79\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f9c38bd9208>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n",
      "Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7fa11c892f60>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py\", line 1455, in __del__\n",
      "    self._session._session, self._handle, status)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.\n"
     ]
    }
   ],
   "source": [
    "hmap_total = make_heatmap(exp_data_tmp)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.colorbar.Colorbar at 0x7f9c3840e470>"
      ]
     },
     "execution_count": 60,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAq0AAAJRCAYAAABvDI7JAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDMuMC4zLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvnQurowAAIABJREFUeJzt3X9wVfWd//HXgQhKayBhCaT3IhBuhBBBgYRkv9vpCtkYQTesGgPqSCj0GwfZgdqpP/b7Fbp0rKTdcaeuQL8bJtWwu02GZXcIoyHEYm271hAD6FayaNRgk5iNQBIQBULu/Xz/sN6aknP5sdx7Lp88HzN3xnw+55x7zsm5Jx9evu/nOMYYIwAAACCODfN6BwAAAIALYdAKAACAuMegFQAAAHGPQSsAAADiHoNWAAAAxD0GrQAAAIh7URu0vvPOO7rlllvCr8TERP34xz9Wd3e38vPzlZ6ervz8fPX09EiSjDFas2aNAoGAZs2apQMHDoS3VVlZqfT0dKWnp6uysjLcvn//fs2cOVOBQEBr1qwRs3cBAADYyYnFPK3BYFA+n0/79u3T5s2blZycrCeeeEJlZWXq6enRD3/4Q9XW1uq5555TbW2t9u3bp7Vr12rfvn3q7u5WVlaWmpqa5DiO5s6dq/379yspKUnz5s3TP/zDPygnJ0eLFi3SmjVrtHDhwmgfDgAAAGIsJuUBe/fu1dSpUzVp0iTV1NSopKREklRSUqKdO3dKkmpqarRs2TI5jqPc3Fz19vaqs7NTe/bsUX5+vpKTk5WUlKT8/HzV1dWps7NTJ0+eVG5urhzH0bJly8LbAgAAgF1iMmitrq7WfffdJ0nq6upSamqqJGnChAnq6uqSJHV0dGjixInhdfx+vzo6OiK2+/3+89oBAABgn4Rov0FfX5927dqljRs3ntfnOI4cx4n2Lqi8vFzl5eWSpDf3v6lRSoz6ewIAgKFhxNhhOnbsmNe7oYL5X9Hx7mBM3utPUm9VXV1dTN7rC1EftO7evVtz5szR+PHjJUnjx49XZ2enUlNT1dnZqZSUFEmSz+dTW1tbeL329nb5fD75fD69+uqrA9pvvfVW+Xw+tbe3n7f8YEpLS1VaWipJSnSSlePkXenDBAAAQ1TP5Favd0GSdLw7qMY9N8TkvebdGftBetTLA6qqqsKlAZJUWFgYngGgsrJSixcvDrdv27ZNxhg1NDRo9OjRSk1NVUFBgerr69XT06Oenh7V19eroKBAqampSkxMVENDg4wx2rZtW3hbAAAAsEtUk9ZPP/1UL7/8sv7xH/8x3PbEE0+ouLhYFRUVmjRpkrZv3y5JWrRokWpraxUIBDRq1Cg9//zzkqTk5GStW7dO2dnZkqT169crOTlZkrRlyxYtX75cp0+f1sKFC5k5AAAADFlGUkghr3cjamIy5VU8oTwAAABcST1zWtXU1OT1bmjuzddq3x7/hRe8AnLvHBPzY456TSsAAABiwSho7E1aeYwrAAAA4h5JKwAAgAU+r2m1t+qTpBUAAABxj6QVAADAEjbPHkDSCgAAgLhH0goAAGABI6OgxTOZkrQCAAAg7pG0AgAAWILZAwAAAAAPMWgFAABA3KM8AAAAwAJGUpDyAAAAAMA7JK0AAACW4ItYAAAAgIdIWgEAACxgJB4uAAAAAHiJpBUAAMASIa93IIpIWgEAABD3SFoBAAAsYGSYpxUAAADwEkkrAACADYwUtDdoJWkFAABA/CNpBQAAsIARswcAAAAAniJpBQAAsIKjoByvdyJqSFoBAAAQ9xi0AgAAIO5RHgAAAGABIynElFcAAACAd0haAQAALMEXsQAAAAAPkbQCAABYwIikFQAAAPAUSSsAAIAlQoakFQAAAPAMSSsAAIAFqGkFAAAAPEbSCgAAYAEjR0GL80h7jwwAAADWIGkFAACwBLMHAAAAAB4iaQUAALAAswcAAAAAHmPQCgAAgLhHeQAAAIAVHAWNvXmkvUcGAAAAa5C0AgAAWMBIClmcR9p7ZAAAALAGSSsAAIAlmPIKAAAA8BBJKwAAgAWMYfYAAAAAwFMkrQAAAJYIUdMKAAAAeIekFQAAwAJGUtDiPNLeIwMAAIA1SFoBAACswOwBAAAAgKdIWgEAACxgJIUsziPtPTIAAABYg0ErAAAA4h7lAQAAAJYIGh4uAAAAAHiGpBUAAMACRg4PFwAAAAC8RNIKAABgiVDMHi5gYvQ+f0DSCgAAgLhH0goAAGABI8WwpjUYo/f5A5JWAAAAxD2SVgAAAAsYOczTerl6e3tVVFSk6dOnKyMjQ6+//rq6u7uVn5+v9PR05efnq6enR5JkjNGaNWsUCAQ0a9YsHThwILydyspKpaenKz09XZWVleH2/fv3a+bMmQoEAlqzZo2MiX1RMAAAAKIvqoPWtWvX6vbbb9fhw4f11ltvKSMjQ2VlZcrLy1NLS4vy8vJUVlYmSdq9e7daWlrU0tKi8vJyrVq1SpLU3d2tDRs2aN++fWpsbNSGDRvCA91Vq1Zp69at4fXq6uqieTgAAABxLaRhMXl5IWrveuLECf3qV7/SypUrJUkjRozQmDFjVFNTo5KSEklSSUmJdu7cKUmqqanRsmXL5DiOcnNz1dvbq87OTu3Zs0f5+flKTk5WUlKS8vPzVVdXp87OTp08eVK5ublyHEfLli0LbwsAAAB2iVpNa2trq8aNG6dvfvObeuuttzR37lw9++yz6urqUmpqqiRpwoQJ6urqkiR1dHRo4sSJ4fX9fr86Ojoitvv9/vPaAQAAhiJjpGDM5mmNvagdWX9/vw4cOKBVq1bp4MGD+spXvhIuBfiC4zhynOgXDJeXlysrK0tZWVk6p7NRfz8AAABcWVEbtPr9fvn9fuXk5EiSioqKdODAAY0fP16dnZ2SpM7OTqWkpEiSfD6f2trawuu3t7fL5/NFbG9vbz+vfTClpaVqampSU1OTrtHIK36sAAAA3nMUitHLC1EbtE6YMEETJ07UO++8I0nau3evZsyYocLCwvAMAJWVlVq8eLEkqbCwUNu2bZMxRg0NDRo9erRSU1NVUFCg+vp69fT0qKenR/X19SooKFBqaqoSExPV0NAgY4y2bdsW3hYAAADsEtV5Wp977jk98MAD6uvrU1pamp5//nmFQiEVFxeroqJCkyZN0vbt2yVJixYtUm1trQKBgEaNGqXnn39ekpScnKx169YpOztbkrR+/XolJydLkrZs2aLly5fr9OnTWrhwoRYuXBjNwwEAAIBHHDPEJjdNdJKV4+R5vRsAAMASPXNa1dTU5PVuaNJN1+v//NucmLzX1gc+jfkx2/sVMwAAAFiDQSsAAIAlghoWk9fFqKur07Rp0xQIBM6bQUqSfve732n+/PmaPXu2Zs2apdra2ojbY9AKAACAKyoYDGr16tXavXu3mpubVVVVpebm5gHLPPXUUyouLtbBgwdVXV2thx9+OOI2GbQCAABYwMhRyMTmdSGNjY0KBAJKS0vTiBEjtHTpUtXU1AxYxnEcnTx5UtLnT1L92te+FnGbUZ09AAAAAEPPYE803bdv34Bl/vZv/1a33XabnnvuOX366af6+c9/HnGbJK0AAACWiFVN69GjR8NPG83KylJ5efkl72tVVZWWL1+u9vZ21dbW6sEHH1QoFHJdnqQVAAAAl2TcuHERp7xye6Lpl1VUVKiurk6S9Kd/+qc6c+aMjh07Fn5a6h8jaQUAALCAkRQyw2LyupDs7Gy1tLSotbVVfX19qq6uVmFh4YBlbrjhBu3du1eS9F//9V86c+aMxo0b57pNBq0AAAC4ohISErRp0yYVFBQoIyNDxcXFyszM1Pr167Vr1y5J0jPPPKOtW7fq5ptv1n333acXXnhBjuP+JS+eiAUAAPA/EC9PxJp402it/dfcmLxX9YPHeSIWAAAA8Mf4IhYAAIAFvqhptZW9RwYAAABrkLQCAABYIqgLP63qakXSCgAAgLhH0goAAGABYxxqWgEAAAAvMWgFAABA3KM8AAAAwBJBygMAAAAA75C0AgAAWMBICjHlFQAAAOAdklYAAAArONS0AgAAAF4iaQUAALCAkRQy1LQCAAAAniFpBQAAsETQ4jzS3iMDAACANUhaAQAALGDkUNMKAAAAeImkFQAAwBIhi/NIe48MAAAA1iBpBQAAsIAxUpCaVgAAAMA7DFoBAAAQ9ygPAAAAsARTXgEAAAAeImkFAACwwOcPF7A3j7T3yAAAAGANklYAAABLBEVNKwAAAOAZklYAAAALGDF7AAAAAOApklYAAAArMHsAAAAA4CmSVgAAAEuEmD0AAAAA8A5JKwAAgAWMkYLMHgAAAAB4h6QVAADAEsweAAAAAHiIQSsAAADiHuUBAAAAFjByeIwrAAAA4CWSVgAAAEvwcAEAAADAQyStAAAAFjASNa0AAACAl0haAQAALMHDBQAAAAAPkbQCAADYwDBPKwAAAOApklYAAAALGDFPKwAAAOApklYAAABLUNMKAAAAeIikFQAAwAI8EQsAAADwGINWAAAAxD3KAwAAACxBeQAAAADgoagOWidPnqyZM2fqlltuUVZWliSpu7tb+fn5Sk9PV35+vnp6eiRJxhitWbNGgUBAs2bN0oEDB8LbqaysVHp6utLT01VZWRlu379/v2bOnKlAIKA1a9bIGBPNwwEAAIhbRp8/xjUWLy9EPWn9xS9+oTfffFNNTU2SpLKyMuXl5amlpUV5eXkqKyuTJO3evVstLS1qaWlReXm5Vq1aJenzQe6GDRu0b98+NTY2asOGDeGB7qpVq7R169bwenV1ddE+HAAAAHgg5uUBNTU1KikpkSSVlJRo586d4fZly5bJcRzl5uaqt7dXnZ2d2rNnj/Lz85WcnKykpCTl5+errq5OnZ2dOnnypHJzc+U4jpYtWxbeFgAAwFAUkhOTlxeiOmh1HEe33Xab5s6dq/LycklSV1eXUlNTJUkTJkxQV1eXJKmjo0MTJ04Mr+v3+9XR0RGx3e/3n9cOAAAA+0R19oD/+I//kM/n08cff6z8/HxNnz59QL/jOHKc6I/Wy8vLw4Pmczob9fcDAACIOcPsAZfN5/NJklJSUnTXXXepsbFR48ePV2dnpySps7NTKSkp4WXb2trC67a3t8vn80Vsb29vP699MKWlpWpqalJTU5Ou0cgrfpwAAACIrqgNWj/99FN98skn4f+ur6/XTTfdpMLCwvAMAJWVlVq8eLEkqbCwUNu2bZMxRg0NDRo9erRSU1NVUFCg+vp69fT0qKenR/X19SooKFBqaqoSExPV0NAgY4y2bdsW3hYAAMBQ88VjXG2dPSBq5QFdXV266667JEn9/f26//77dfvttys7O1vFxcWqqKjQpEmTtH37dknSokWLVFtbq0AgoFGjRun555+XJCUnJ2vdunXKzs6WJK1fv17JycmSpC1btmj58uU6ffq0Fi5cqIULF0brcAAAAOAhxwyxyU0TnWTlOHle7wYAALBEz5zW8NSeXkqcNl7Z/++BmLzXiUd/FfNj5olYAAAAiHtRnT0AAAAAsfHFE7FsRdIKAACAuEfSCgAAYAlD0goAAAB4h0ErAAAA4h7lAQAAAJYIifIAAAAAwDMkrQAAABYwRkx5BQAAAHiJpBUAAMASTHkFAAAAeIikFQAAwAo8xhUAAADwFEkrAACAJahpBQAAADxE0goAAGABI+ZpBQAAADxF0goAAGAD8/lTsWxF0goAAIC4R9IKAABgiZBiU9PqReUsSSsAAADiHoNWAAAAxD3KAwAAACxgFLuHC1AeAAAAAAyCpBUAAMAKTsweLuBF6knSCgAAgLhH0goAAGAJHi4AAAAAeIikFQAAwBKxmj3ACyStAAAAiHskrQAAABYwhqQVAAAA8BRJKwAAgCViNU+rF0haAQAAcMXV1dVp2rRpCgQCKisrG3SZ7du3a8aMGcrMzNT9998fcXskrQAAAJaIl3lag8GgVq9erZdffll+v1/Z2dkqLCzUjBkzwsu0tLRo48aNeu2115SUlKSPP/444jZJWgEAAHBFNTY2KhAIKC0tTSNGjNDSpUtVU1MzYJmtW7dq9erVSkpKkiSlpKRE3CaDVgAAAEsY48TkdSEdHR2aOHFi+Ge/36+Ojo4By7z77rt699139Wd/9mfKzc1VXV1dxG1SHgAAAIBLcvToUWVlZYV/Li0tVWlp6SVto7+/Xy0tLXr11VfV3t6ub3zjG/rtb3+rMWPGDLo8g1YAAABcknHjxqmpqcm13+fzqa2tLfxze3u7fD7fgGX8fr9ycnJ0zTXXaMqUKbrxxhvV0tKi7OzsQbdJeQAAAIAFjGJTGnAx5QHZ2dlqaWlRa2ur+vr6VF1drcLCwgHL/NVf/ZVeffVVSdKxY8f07rvvKi0tzXWbDFoBAABwRSUkJGjTpk0qKChQRkaGiouLlZmZqfXr12vXrl2SpIKCAo0dO1YzZszQ/Pnz9Xd/93caO3as6zYdY+JlcoTYSHSSlePkeb0bAADAEj1zWiP+r/JYuTbg06QfPRST97r+6V0xP2aSVgAAAMQ9vogFAABgA6OLqje9WpG0AgAAIO6RtAIAANjC4m8qkbQCAAAg7pG0AgAAWIKaVgAAAMBDJK0AAACWsHn2fZJWAAAAxD2SVgAAAAsYUdMKAAAAeIqkFQAAwAZGEkkrAAAA4B0GrQAAAIh7lAcAAABYgimvAAAAAA+RtAIAANiCpBUAAADwDkkrAACAFRweLgAAAAB4iaQVAADAFtS0AgAAAN4haQUAALCBETWtAAAAgJdIWgEAAGxBTSsAAADgHZJWAAAAa1DTCgAAAHgm6oPWYDCo2bNn684775Qktba2KicnR4FAQEuWLFFfX58k6ezZs1qyZIkCgYBycnJ05MiR8DY2btyoQCCgadOmac+ePeH2uro6TZs2TYFAQGVlZdE+FAAAgPhmYvTyQNQHrc8++6wyMjLCPz/++ON65JFH9N577ykpKUkVFRWSpIqKCiUlJem9997TI488oscff1yS1NzcrOrqah06dEh1dXV6+OGHFQwGFQwGtXr1au3evVvNzc2qqqpSc3NztA8HAAAAHojqoLW9vV0vvfSSvvWtb0mSjDF65ZVXVFRUJEkqKSnRzp07JUk1NTUqKSmRJBUVFWnv3r0yxqimpkZLly7VyJEjNWXKFAUCATU2NqqxsVGBQEBpaWkaMWKEli5dqpqammgeDgAAADwS1UHrt7/9bf3oRz/SsGGfv83x48c1ZswYJSR8/v0vv9+vjo4OSVJHR4cmTpwoSUpISNDo0aN1/PjxAe1fXsetHQAAYMiiPODSvfjii0pJSdHcuXOj9RYXrby8XFlZWcrKytI5nfV6dwAAAHCJojbl1WuvvaZdu3aptrZWZ86c0cmTJ7V27Vr19vaqv79fCQkJam9vl8/nkyT5fD61tbXJ7/erv79fJ06c0NixY8PtX/jyOm7tf6y0tFSlpaWSpEQnOVqHDAAA4B0jice4XrqNGzeqvb1dR44cUXV1tRYsWKB/+Zd/0fz587Vjxw5JUmVlpRYvXixJKiwsVGVlpSRpx44dWrBggRzHUWFhoaqrq3X27Fm1traqpaVF8+bNU3Z2tlpaWtTa2qq+vj5VV1ersLAwWocDAAAAD8X84QI//OEPtXTpUj355JOaPXu2Vq5cKUlauXKlHnzwQQUCASUnJ6u6ulqSlJmZqeLiYs2YMUMJCQnavHmzhg8fLknatGmTCgoKFAwGtWLFCmVmZsb6cAAAAOKGsfgxro4xNh/e+RKdZOU4eV7vBgAAsETPnFY1NTV5vRsaOdmvCevXxOS9xm3ZHvNj5jGuAAAAtrA4iuQxrgAAAIh7JK0AAAC2YPYAAAAAwDskrQAAAJZwqGkFAAAAvEPSCgAAYAMjZg8AAAAAvETSCgAAYAWH2QMAAAAALzFoBQAAQNyjPAAAAMAWfBELAAAA8A5JKwAAgC1IWgEAAADvkLQCAADYgqQVAAAA8A5JKwAAgA2MeLgAAAAA4CWSVgAAAEs41LQCAAAA3iFpBQAAsAVJKwAAAOAdBq0AAACIewxaAQAAEPcuedB67NgxGWNxwQQAAMBVyjGxeXkh4qC1oaFBt956q+6++24dPHhQN910k2666SaNHz9edXV1sdpHAAAADHERZw/467/+az399NM6ceKEFixYoN27dys3N1eHDx/Wfffdp9tvvz1W+wkAAIALGapPxOrv79dtt92me++9VxMmTFBubq4kafr06THZOQAAAEC6wKB12LA/dF933XUD+hzH3pE8AAAA4kvE8oC33npLiYmJMsbo9OnTSkxMlCQZY3TmzJmY7CAAAAAugpHVDxeIOGgNBoOx2g8AAADAFY9xBQAAsIXFSSsPFwAAAEDcI2kFAACwhFcT/8cCSSsAAADiHkkrAACALUhaAQAAAO+QtAIAANiCpBUAAADwDkkrAACABRzD7AEAAACAp0haAQAAbGEcr/cgakhaAQAAEPdIWgEAAGxBTSsAAADgHQatAAAAiHuUBwAAAFiCKa8AAAAAD5G0AgAA2IKkFQAAAPAOSSsAAIANeIwrAAAA4C2SVgAAAFuQtAIAAADeIWkFAACwBUkrAAAA4B2SVgAAAEswewAAAADgIQatAAAAiHsMWgEAABD3qGkFAACwBTWtAAAAgHcYtAIAACDuUR4AAABgA8OUVwAAAICnSFoBAABsQdIKAAAAeIdBKwAAgC1MjF4Xoa6uTtOmTVMgEFBZWZnrcv/2b/8mx3HU1NQUcXsMWgEAAHBFBYNBrV69Wrt371Zzc7OqqqrU3Nx83nKffPKJnn32WeXk5FxwmwxaAQAALODo89kDYvG6kMbGRgUCAaWlpWnEiBFaunSpampqzltu3bp1evzxx3XttddecJtRG7SeOXNG8+bN080336zMzEx973vfkyS1trYqJydHgUBAS5YsUV9fnyTp7NmzWrJkiQKBgHJycnTkyJHwtjZu3KhAIKBp06Zpz5494faLjZ0BAAAQOx0dHZo4cWL4Z7/fr46OjgHLHDhwQG1tbbrjjjsuaptRG7SOHDlSr7zyit566y29+eabqqurU0NDgx5//HE98sgjeu+995SUlKSKigpJUkVFhZKSkvTee+/pkUce0eOPPy5Jam5uVnV1tQ4dOqS6ujo9/PDDCgaDFx07AwAADBkxqmk9evSosrKywq/y8vJL2s1QKKTvfOc7euaZZy56nagNWh3H0Ve/+lVJ0rlz53Tu3Dk5jqNXXnlFRUVFkqSSkhLt3LlTklRTU6OSkhJJUlFRkfbu3StjjGpqarR06VKNHDlSU6ZMUSAQUGNj40XHzgAAALiyxo0bp6ampvCrtLR0QL/P51NbW1v45/b2dvl8vvDPn3zyid5++23deuutmjx5shoaGlRYWBjxy1hRrWkNBoO65ZZblJKSovz8fE2dOlVjxoxRQsLn08N+OSr+coyckJCg0aNH6/jx467x8sXEzgAAAENGjOpZL6amNTs7Wy0tLWptbVVfX5+qq6tVWFgY7h89erSOHTumI0eO6MiRI8rNzdWuXbuUlZXlus2oDlqHDx+uN998U+3t7WpsbNThw4ej+XauysvLw/H1OZ31ZB8AAACGioSEBG3atEkFBQXKyMhQcXGxMjMztX79eu3atevytnmF93FQY8aM0fz58/X666+rt7dX/f39SkhIGBAVfxEj+/1+9ff368SJExo7dmzEeDlS7PxlpaWl4dg60UmO1mECAAB4K46eiLVo0SItWrRoQNv3v//9QZd99dVXL7i9qCWtR48eVW9vryTp9OnTevnll5WRkaH58+drx44dkqTKykotXrxYklRYWKjKykpJ0o4dO7RgwQI5jqPCwkJVV1fr7Nmzam1tVUtLi+bNm3fB2BkAAAD2iFrS2tnZqZKSEgWDQYVCIRUXF+vOO+/UjBkztHTpUj355JOaPXu2Vq5cKUlauXKlHnzwQQUCASUnJ6u6ulqSlJmZqeLiYs2YMUMJCQnavHmzhg8fLknh2DkYDGrFihXKzMyM1uEAAADEvzhKWq80xxhj8eGdL9FJVo6T5/VuAAAAS/TMab3gI0hj4brUiZryze/E5L1G1f9LzI+ZJ2IBAAAg7sXki1gAAACIvouZjupqRdIKAACAuEfSCgAAYAuSVgAAAMA7JK0AAAA2MCJpBQAAALxE0goAAGAJZg8AAAAAPETSCgAAYAuSVgAAAMA7JK0AAACWoKYVAAAA8BBJKwAAgC1IWgEAAADvkLQCAADYgCdiAQAAAN5i0AoAAIC4R3kAAACABZzfv2xF0goAAIC4R9IKAABgC76IBQAAAHiHpBUAAMASPMYVAAAA8BBJKwAAgC1IWgEAAADvkLQCAADYgqQVAAAA8A5JKwAAgA0MswcAAAAAniJpBQAAsAVJKwAAAOAdklYAAABLUNMKAAAAeIhBKwAAAOIe5QEAAAC2oDwAAAAA8A5JKwAAgCX4IhYAAADgIZJWAAAAGxhR0woAAAB4iaQVAADAFiStAAAAgHdIWgEAACzgiNkDAAAAAE+RtAIAANiCpBUAAADwDkkrAACAJRxjb9RK0goAAIC4R9IKWK7lhbmufenL98dwT2CLlsoI11QJ1xTgGZ6IBQAAAHiLQSsAAADiHuUBAAAAlojVwwW8qEIgaQUAAEDcI2kFAACwBV/EAgAAALxD0goAAGAJaloBAAAAD5G0AgAA2IKaVgAAAMA7JK0AAAA2MLGrafUCSSsAAADiHkkrAACALUhaAQAAAO+QtAIAAFjAETWtAAAAgKdIWgEAAGxh7I1aSVoBAAAQ9xi0AgAAIO5RHgAAAGAJvogFAAAAeChqg9a2tjbNnz9fM2bMUGZmpp599llJUnd3t/Lz85Wenq78/Hz19PRIkowxWrNmjQKBgGbNmqUDBw6Et1VZWan09HSlp6ersrIy3L5//37NnDlTgUBAa9askbG4+BgAACAiE8OXB6I2aE1ISNAzzzyj5uZmNTQ0aPPmzWpublZZWZny8vLU0tKivLw8lZWVSZJ2796tlpYWtbS0qLy8XKtWrZL0+SB3w4YN2rdvnxobG7Vhw4bwQHfVqlXaunVreL26urpoHQ4AAAA8FLVRXDpiAAAZqUlEQVRBa2pqqubMmSNJuv7665WRkaGOjg7V1NSopKREklRSUqKdO3dKkmpqarRs2TI5jqPc3Fz19vaqs7NTe/bsUX5+vpKTk5WUlKT8/HzV1dWps7NTJ0+eVG5urhzH0bJly8LbAgAAGIqcUGxeXohJTeuRI0d08OBB5eTkqKurS6mpqZKkCRMmqKurS5LU0dGhiRMnhtfx+/3q6OiI2O73+89rBwAAgH2iPnvAqVOndM899+jHP/6xEhMTB/Q5jiPHcaK9CyovL1d5ebkk6ZzORv39AAAAPGHx13uimrSeO3dO99xzjx544AHdfffdkqTx48ers7NTktTZ2amUlBRJks/nU1tbW3jd9vZ2+Xy+iO3t7e3ntQ+mtLRUTU1Nampq0jUaecWPEwAAANEVtUGrMUYrV65URkaGvvOd74TbCwsLwzMAVFZWavHixeH2bdu2yRijhoYGjR49WqmpqSooKFB9fb16enrU09Oj+vp6FRQUKDU1VYmJiWpoaJAxRtu2bQtvCwAAYChyTGxeXohaecBrr72mf/qnf9LMmTN1yy23SJKefvppPfHEEyouLlZFRYUmTZqk7du3S5IWLVqk2tpaBQIBjRo1Ss8//7wkKTk5WevWrVN2drYkaf369UpOTpYkbdmyRcuXL9fp06e1cOFCLVy4MFqHAwAAAA9FbdD69a9/3XXe1L17957X5jiONm/ePOjyK1as0IoVK85rz8rK0ttvv/0/21EAAAAbGEkWz1nPE7EAAAAQ96I+ewAAAABiw6t601ggaQUAAEDcI2kFLJe+fL/XuwDLpJdwTQFxi6QVAAAA8A6DVgAAAMQ9ygMAAAAs4IgvYgEAAACeImkFAACwgTE8XAAAAADwEkkrAACAJahpBQAAADxE0goAAGALklYAAADAOyStAAAAlqCmFQAAAPAQSSsAAIANjKSQvVErSSsAAADiHkkrAACALewNWklaAQAAEP9IWgEAACzB7AEAAADAJairq9O0adMUCARUVlZ2Xv/f//3fa8aMGZo1a5by8vL04YcfRtweg1YAAABcUcFgUKtXr9bu3bvV3NysqqoqNTc3D1hm9uzZampq0n/+53+qqKhIjz32WMRtMmgFAACwhTGxeV1AY2OjAoGA0tLSNGLECC1dulQ1NTUDlpk/f75GjRolScrNzVV7e3vEbTJoBQAAwBXV0dGhiRMnhn/2+/3q6OhwXb6iokILFy6MuE2+iAUAAGCJWH0R6+jRo8rKygr/XFpaqtLS0sva1j//8z+rqalJv/zlLyMux6AVAAAAl2TcuHFqampy7ff5fGprawv/3N7eLp/Pd95yP//5z/WDH/xAv/zlLzVy5MiI70l5AAAAgA1MDF8XkJ2drZaWFrW2tqqvr0/V1dUqLCwcsMzBgwf10EMPadeuXUpJSbngNhm0AgAA4IpKSEjQpk2bVFBQoIyMDBUXFyszM1Pr16/Xrl27JEmPPvqoTp06pXvvvVe33HLLeYPaP+YYcxFfAbNIopOsHCfP690AAACW6JnTGvF/lcdKYqJfWTl/HZP3OtmzI+bHTNIKAACAuMcXsQAAAGwR8noHooekFQAAAHGPpBUAAMASjsVfVSJpBQAAQNwjaQUAALDBRc6herUiaQUAAEDcG3JJ642zPtOePW+d117wtZtd10kY7/KUhv6g6zrvrEt37Ut62/3fCskVDa59bhJuOP+xaGGnz7h2Hf6/U137ti9+btD2/zMlx3WdYddd696XMs6177Pp7k/BODH1mkHbr293P/fX1uxz7XP9XUrS8OGDNrf+7ynu2/vUfXOpz0T4XRr3r3cmTHV5v89Ou65z8k8nufY5Eb5Jet3Owc/V8DFj3FfyuZ/DT6e6r9d2t/vvbML4E4O2X7/oA9d1ElLHu/YpQk3X+6vTXPv6Rg9+sqZ/7x3XdUInTrr2DZ800bVPn5watLn14RtdV7lm8NMkSUp9zv26d0aMcO0b5nL/+PTGZNd1cr/f6Nq3/Tfu94j01YPv4+V8LiXpcFmqa585Nfi9Q5KmP3Zo0PbgqcF/J5KU4L+8++y7fzP473NEj+O6zsSyCL/LCOdj2JQbXPtOZo4dtP3jJe777gxz/xxNKn7btS9hQoTfZ2jwz9g7j7v/PQpd534Ty/jhf7uv19k1aPuwCe5/jyJdb+8+7H69Jf2s1X2bMWUi3v+udiStAAAAiHtDLmkFAACwlWNv0ErSCgAAgPjHoBUAAABxj/IAAAAAW/BFLAAAAMA7JK0AAAA2MJGnObzakbQCAAAg7pG0AgAA2IKaVgAAAMA7JK0AAAC2sDdoJWkFAABA/CNpBQAAsIRDTSsAAADgHZJWAAAAW5C0AgAAAN4haQUAALCBkcQTsQAAAADvkLQCAABYwJFh9gAAAADASwxaAQAAEPcoDwAAALAF5QEAAACAd0haAQAAbBGrpNWJzdt8GUkrAAAA4h5JKwAAgA1i+XCB4TF6ny8haQUAAEDcI2kFAACwBA8XAAAAADxE0goAAGALklYAAADAOyStAAAAVjAkrQAAAICXopa0rlixQi+++KJSUlL09ttvS5K6u7u1ZMkSHTlyRJMnT9b27duVlJQkY4zWrl2r2tpajRo1Si+88ILmzJkjSaqsrNRTTz0lSXryySdVUlIiSdq/f7+WL1+u06dPa9GiRXr22WflOBd+PMPJkKOXT1/aYZvPTg/a7oxNdl1n3Bvu+3L8Lz917Rvz3i2ufcNePTB4x+kzruvommtcu0b0uv+b5f6frR20fbIaXNcJRdgP57qRrn3X/uqQa1/7X9w8aPsnk9z3PbB7hGtf6JNTrn3Dxo0dtP2rbe7/aj33Vfff8/AZAde+4KF3Xfvkcr0pdHmT7330DfdzNbVm8L7giZOu6wz3pbj2feVX7sc1cs4M177OvsE/S6Ov7XBdx5z8xLXPGT/OtS/xffff57Fbzw3a/t6jGa7rTPmb37j26Wyfe9+Iwa/TUITb06kpEa4Bx/33HDpz1rVvWGjw8/GV37zvus6OQ7Nd+8xI9310hg8+sWPEz+UNPte+1F3un/X5T77m2pfSOPj1/eKMJNd1FAy69yW4T1g5/PTg94iz4yKcp5Hu98vQZ5+59kVKoRJf/3DQ9o/+fLLrOibB/bPi9ruUpFCE+8ew5MHPcep/uJ+PEQ93uvdtc7+2P/vG4H+ThkX6m3n9V127rjnhwSOgLpURSevlWL58uerq6ga0lZWVKS8vTy0tLcrLy1NZWZkkaffu3WppaVFLS4vKy8u1atUqSZ8Pcjds2KB9+/apsbFRGzZsUE9PjyRp1apV2rp1a3i9P34vAAAA2CNqg9ZvfOMbSk4emJ7U1NSEk9KSkhLt3Lkz3L5s2TI5jqPc3Fz19vaqs7NTe/bsUX5+vpKTk5WUlKT8/HzV1dWps7NTJ0+eVG5urhzH0bJly8LbAgAAGLJCMXp5IKY1rV1dXUpNTZUkTZgwQV1dXZKkjo4OTZw4Mbyc3+9XR0dHxHa/339eOwAAAOzk2ewBjuNcVA3qlVBeXq7y8nJJ0onu/pi8JwAAAK6cmCat48ePV2fn5wXVnZ2dSkn5/AsdPp9PbW1t4eXa29vl8/kitre3t5/X7qa0tFRNTU1qamrS6GRm+QIAAHZyjInJywsxHbQWFhaqsrJS0uezAixevDjcvm3bNhlj1NDQoNGjRys1NVUFBQWqr69XT0+Penp6VF9fr4KCAqWmpioxMVENDQ0yxmjbtm3hbQEAAMA+UYsd77vvPr366qs6duyY/H6/NmzYoCeeeELFxcWqqKjQpEmTtH37dknSokWLVFtbq0AgoFGjRun555+XJCUnJ2vdunXKzs6WJK1fvz785a4tW7aEp7xauHChFi5cGK1DAQAAuDpYPOVV1AatVVVVg7bv3bv3vDbHcbR58+ZBl1+xYoVWrFhxXntWVlZ4/lcAAADYjQJPAAAAGxhJLg8MsQGPcQUAAEDcI2kFAACwgrG6ppWkFQAAAHGPpBUAAMAWJK0AAACAd0haAQAAbEHSCgAAAHiHpBUAAMAGzNMKAAAAeIukFQAAwApGMiGvdyJqSFoBAAAQ9xi0AgAAIO5RHgAAAGALprwCAAAAvEPSCgAAYAOmvAIAAAC8RdIKAABgC2paAQAAAO+QtAIAANiCpBUAAADwDkkrAACAFQxJKwAAAOAlklYAAAAbGEmhkNd7ETUkrQAAAIh7jjEWFz8MYvTwP1HudXec1x767LNL3tawESNc+0Ln+l37ct/sc+07G3IPv//kmlODto8cds51nXNmuGvfZ8GRrn2jhp8dtH3McPfz1N6X7No3evhp176uc4mufckJnw7a/knwWtd1Ukf0uvadCF7n2nf9sDODtg9z3D8iIxz333PQuP+bMNJ5bDvnfh7dfHj6T1z7Dme5X29uUl4f49r3Wb/7dT/t+i7XvuFy/9d/yoiTg7anjfjYdZ1PQu6/y68MG/z6laTrh7lfi2fMNYO2X6Og6zohOa59h89+zbXv477Br/tRw91/Xz39X3HtCxr3/YgkdBnrRbqvTL72uGvfZ6HBr51In5WGW9yvt/v+q8O1b8zwwe8dktQd/Oqg7WdCg//+pcj3gVMR7kdu9yq3e5sU+Z4eSaTP2LH+6wdvPzf4uZCkG0Z2u/bV3pTkviPmCid9ToR87Uq/12XuR8/s99XU1BS7fXEx+poU/a+xRTF5r6P+xpgfM0krAAAA4h41rQAAALaw+H+gk7QCAAAg7jFoBQAAQNyjPAAAAMAKRgpRHgAAAAB4hqQVAADABkYysZwGLMZIWgEAABD3SFoBAABsQU0rAAAA4B2SVgAAAFvwcAEAAADAOyStAAAANjBGCjF7AAAAAOAZklYAAABbUNMKAAAAeIekFQAAwBKGmlYAAADAOyStAAAAVjDUtAIAAABeYtAKAACAuEd5AAAAgA2MpBDlAQAAAIBnSFoBAABsYZjyCgAAAPAMSSsAAIAFjCRDTSsAAADgHZJWAAAAGxhDTSsAAADgJQatAAAAljAhE5PXxairq9O0adMUCARUVlZ2Xv/Zs2e1ZMkSBQIB5eTk6MiRIxG3x6AVAAAAV1QwGNTq1au1e/duNTc3q6qqSs3NzQOWqaioUFJSkt577z098sgjevzxxyNuk0ErAACALUwoNq8LaGxsVCAQUFpamkaMGKGlS5eqpqZmwDI1NTUqKSmRJBUVFWnv3r0yxj3FZdAKAACAK6qjo0MTJ04M/+z3+9XR0eG6TEJCgkaPHq3jx4+7bnPIzR4QvO6Mjk8/5Ok+7P6mp28fRZ9fjEePHtW4ceMuYb3u6OzOoD6J4XtdLvcP7BfOP8cR1plz6XvQs/rS15GktstbLYIREfqCEfoi3dquv6h3vvTreDC9l9l39Wq8xOUveJ5nu3dtuT/SlodH6Dt9ie0XEt/3lStzLf+R2bG8b8e/w4cPe70LkqT/VTBPx461xuS9Tp8+raysrPDPpaWlKi0tjep7DrlB6/Tp09XU1OT1blgtKyuLcxxlnOPo4xzHBuc5+jjH0fflwZuX6urqvN6FMJ/Pp7a2P0QZ7e3t8vl8gy7j9/vV39+vEydOaOzYsa7bpDwAAAAAV1R2drZaWlrU2tqqvr4+VVdXq7CwcMAyhYWFqqyslCTt2LFDCxYskOM4rtscckkrAAAAoishIUGbNm1SQUGBgsGgVqxYoczMTK1fv15ZWVkqLCzUypUr9eCDDyoQCCg5OVnV1dWRtxmjfY8b0a63AOc4FjjH0cc5jg3Oc/RxjqOPczy4RYsWadGiRQPavv/974f/+9prr9W//uu/XvT2HBNpbgEAAAAgDlDTCgAAgLhnxaD1ueee0/Tp05WZmanHHnss3L5x40YFAgFNmzZNe/bsCbe7PVastbVVOTk5CgQCWrJkifr6+iRd+mPGbPXMM8/IcRwdO3ZMkmSM0Zo1axQIBDRr1iwdOHAgvGxlZaXS09OVnp4eLrKWpP3792vmzJkKBAJas2ZNeBLh7u5u5efnKz09Xfn5+erp6YntwXns0Ucf1fTp0zVr1izddddd6u39w3RIXMexd6FHD2KgtrY2zZ8/XzNmzFBmZqaeffZZSe6f6yt57xhqgsGgZs+erTvvvFPS5X3eL/WeMpT09vaqqKhI06dPV0ZGhl5//XWu43hirnKvvPKKycvLM2fOnDHGGNPV1WWMMebQoUNm1qxZ5syZM+aDDz4waWlppr+/3/T395u0tDTz/vvvm7Nnz5pZs2aZQ4cOGWOMuffee01VVZUxxpiHHnrIbNmyxRhjzObNm81DDz1kjDGmqqrKFBcXx/owPfe73/3O3HbbbeaGG24wR48eNcYY89JLL5nbb7/dhEIh8/rrr5t58+YZY4w5fvy4mTJlijl+/Ljp7u42U6ZMMd3d3cYYY7Kzs83rr79uQqGQuf32201tba0xxphHH33UbNy40RhjzMaNG81jjz3mwVF6Z8+ePebcuXPGGGMee+yx8PFzHcdepHOLwX300Udm//79xhhjTp48adLT082hQ4dcP9dX8t4x1DzzzDPmvvvuM3fccYcx5tI/75dzTxlKli1bZrZu3WqMMebs2bOmp6eH6ziOXPWD1nvvvde8/PLL57U//fTT5umnnw7/fNttt5nf/OY35je/+Y257bbbzlsuFAqZsWPHhgcOX17ui3WNMebcuXNm7NixJhQKRfOw4s4999xj3nzzTTNp0qTwoLW0tNT87Gc/Cy9z4403mo8++sj87Gc/M6WlpeH2L5b76KOPzLRp08LtX17ui3WN+fwP4I033hiLw4pL//7v/27uv/9+YwzXsRfczi0uXmFhoamvr3f9XF/Je8dQ0tbWZhYsWGD27t1r7rjjjsv6vF/qPWUo6e3tNZMnTz7vvsh1HD+u+vKAd999V7/+9a+Vk5OjP//zP9cbb7whyf3xYW7tx48f15gxY5SQkDCg/Y+3dTGPGbNNTU2NfD6fbr755gHtl3qOOzo65Pf7z2uXpK6uLqWmpkqSJkyYoK6urmgeUlz76U9/qoULF0riOvbCxTx6EO6OHDmigwcPKicnx/VzfSXvHUPJt7/9bf3oRz/SsGGf/+m+nM/7pZ77oaS1tVXjxo3TN7/5Tc2ePVvf+ta39Omnn3Idx5GrYsqrv/iLv9B///d/n9f+gx/8QP39/eru7lZDQ4PeeOMNFRcX64MPPvBgL69ukc7x008/rfr6+pjti+M4EScXvlpFOseLFy8O/3dCQoIeeOCBWO8e8D926tQp3XPPPfrxj3+sxMTEAX22fq5j5cUXX1RKSormzp2rV1991evdsVJ/f78OHDig5557Tjk5OVq7du15tb1cx966KgatP//5z137fvKTn+juu++W4ziaN2+ehg0bpmPHjkV8fNhg7WPHjlVvb6/6+/uVkJAwYPlLfczY1cjtHP/2t79Va2trOGVtb2/XnDlz1NjY6HqOfT7fgJtqe3u7br31Vvl8PrW3t5+3vCSNHz9enZ2dSk1NVWdnp1JSUqJwlN6KdB1L0gsvvKAXX3xRe/fuDd8UuY5j72IePYjznTt3Tvfcc48eeOAB3X333ZLcP9dX8t4xVLz22mvatWuXamtrdebMGZ08eVJr16695M/7pd5ThhK/3y+/36+cnBxJUlFRkcrKyriO44nX9Qn/Uz/5yU/MunXrjDHGvPPOO8bv95tQKGTefvvtAcXmU6ZMMf39/ebcuXNmypQp5oMPPggXm7/99tvGGGOKiooGFLRv3rzZGGPMpk2bBhS033vvvR4caXz4ck3riy++OKAIPTs72xjzeRH65MmTTXd3t+nu7jaTJ082x48fN8acX4T+0ksvGWOM+e53vzug0P3RRx/14Oi8s3v3bpORkWE+/vjjAe1cx7EX6dxicKFQyDz44INm7dq1A9rdPtdX8t4xFP3iF78IfxHrUj/vl3NPGUq+/vWvm8OHDxtjjPne975nvvvd73Idx5GrftB69uxZ88ADD5jMzEwze/Zss3fv3nDfU089ZdLS0syNN9444Bt6L730kklPTzdpaWnmqaeeCre///77Jjs720ydOtUUFRWFZyQ4ffq0KSoqMlOnTjXZ2dnm/fffj90BxpkvD1pDoZB5+OGHTVpamrnpppvMG2+8EV6uoqLCTJ061UydOtX89Kc/Dbe/8cYbJjMz06SlpZnVq1eHC96PHTtmFixYYAKBgMnLywt/wIeKqVOnGr/fb26++WZz8803h//YGMN17AW3c4vB/frXvzaSzMyZM8PX8EsvveT6ub6S946h6MuD1sv5vF/qPWUoOXjwoJk7d66ZOXOmWbx4senu7uY6jiM8EQsAAABx76qfPQAAAAD2Y9AKAACAuMegFQAAAHGPQSsAAADiHoNWAAAAxD0GrQDwR3bu3CnHcXT48GGvdwUA8HsMWgHgj1RVVenrX/+6qqqqvN4VAMDvMU8rAHzJqVOnNG3aNP3iF7/QX/7lX+qdd97xepcAACJpBYABampqdPvtt+vGG2/U2LFjtX//fq93CQAgBq0AMEBVVZWWLl0qSVq6dCklAgAQJygPAIDf6+7ult/v17hx4+Q4joLBoBzH0YcffijHcbzePQAY0khaAeD3duzYoQcffFAffvihjhw5ora2Nk2ZMkW//vWvvd41ABjyGLQCwO9VVVXprrvuGtB2zz33UCIAAHGA8gAAAADEPZJWAAAAxD0GrQAAAIh7DFoBAAAQ9xi0AgAAIO4xaAUAAEDcY9AKAACAuMegFQAAAHGPQSsAAADi3v8HItkcA8mYVq8AAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 864x720 with 2 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "A_list = np.linspace(-60000, 60000, 80)\n",
    "B_list = np.linspace(2000, 70000, 17)\n",
    "fig = plt.figure(figsize=(12, 10), facecolor='w')        \n",
    "ax = fig.add_subplot(1, 1, 1)\n",
    "pc = ax.pcolor(A_list, B_list, hmap_total.transpose())\n",
    "# ax.colorbar()\n",
    "ax.set_xlabel('A')\n",
    "ax.set_ylabel('B')\n",
    "plt.colorbar(pc)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
